server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jap:
    hibernate:
      ddl-auto: create
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true #sql 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화

    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기합을 100MB 제한


logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.app: debug # todo 패키지 수정

cloud:
  openfeign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000

kakao:
  client:
    id: ENC(ZAT8W9PQWwnHRsI3Zr47NqtDYSD7KSkUPDVDA9lIy2jGUJXvf2O+bgxtScqUOa92)
    secret: ENC(iGH8FUl46MrZj//cJiXqtxhQvqfHTuafJN0QeT0fC5CApfXrm5yNQ1aZft/N0H3z)

token:
  secret: ENC(/II1dwF6D7DDI3CAf8a5zTTqtKN8nm4rKl9HWHmLtMs=) # 임의의 문자열
  access-token-expiration-time: 900000 # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

jasypt:
  password: ${PASSWORD}